### PR TITLE
Fix apigateway+lambda timeout issue

### LINKED ISSUE #91: Fix Api Gateway Lambda integration timeout issue
Currently, Essentially use API Gateway + Lambda integration for the API deployment. However, this solution suffers from a timeout issue. More specifically, API Gateway's timeout is capped at 30 seconds ([ref](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html)), and the Lambda function might not be able to finish processing the request within that time.

### PR DESCRIPTION
**Pull request by Michaeltaoma**
fixed #91 

1. Add another apigateway+lambda function (`summaryRequest`) to 
    1. Take in summary request
    2. Asynchronously call the summary lambda to process the summary
    3. Return the file path for the client to look
2. Modify current `summary` lambda function to upload the summarization result to s3 bucket after it's done
3. Modify the way to get summary in the testing page created in [this pr](https://github.com/ubclaunchpad/Essentially/pull/78) so that the client first makes a request to the `summaryRequest` API and then keep trying fetching from the file path

Tested with the testing webpage. To test the functionality yourself, build the frontend and run `npm run start:web`, the testing webpage is hosted on `http://localhost:8080/`.

### CODE REVIEW

File: backend/src/summary.ts [hunk 1]
```diff
@@ -1,50 +1,79 @@
...
+          "essentially-backend-s3st-essentiallybackendtestbu-1e6w7ixe3uqi0",
+        Key: body.summaryId.concat("/summary.json"),
+        Body: JSON.stringify({
+          summarized_text: payload.summarized_text,
+          meta: payload.Meta,
+        }),
+        ContentType: "application/json",
+      })
+      .promise();
+    return {
```
Comment (Hgjnnf) [inline backend/src/summary.ts:62]: If we are fetching the summary from s3, is it still necessary to return a body with the summarized text?

File: backend/src/summary.ts [hunk 2]
```diff
@@ -1,50 +1,79 @@
...
+  } catch {
+    body = event.body;
+  }
+
+  if (!body || !body.content || !body.length || !body.summaryId) {
+    return {
+      statusCode: 400,
+      headers: CORS_HEADER,
+      body: JSON.stringify(
+        "Invalid Request - Please supply some text and length to summarize."
```
Comment (Hgjnnf) [inline backend/src/summary.ts]: We can add to the error message by mentioning summaryId.

File: frontend/src/pages/summaryPage.tsx [hunk 3]
```diff
@@ -16,21 +17,32 @@ export default function SummaryPage({
...
+        if (res.status === 200) {
+          clearInterval(interval);
+          res.json().then(data => {
+            setSummary([data.summarized_text]);
+            setSummaryIsLoading(false);
+            setGenerateTime(Date.now() - time);
+          })
+        }
+      })
+    }, 100);
```
Comment (Hgjnnf) [inline frontend/src/pages/summaryPage.tsx]: Fetching every 100ms is too much. I think we could raise it to every 3 seconds, or something similar. What do you think?

File: frontend/src/pages/summaryPage.tsx [hunk 4]
```diff
@@ -16,21 +17,32 @@ export default function SummaryPage({
...
       .then((res) => res.json())
       .then((data) => {
-        setSummary([data.summarized_text]);
-        setSummaryIsLoading(false);
-        setGenerateTime(Date.now() - time);
+        return data.summaryPath;
       });
+    const interval = setInterval(() => {
+      fetch(summaryPath).then((res) => {
+        if (res.status === 200) {
```
Comment (Hgjnnf) [inline frontend/src/pages/summaryPage.tsx:36]: Is it possible to remove the summary.json after the summary state is set? We can reduce a lot of storage usage.

**Review by Hgjnnf — CHANGES_REQUESTED** [review]
This works really well! I added some comments with changes that I think we should address before merging.

File: frontend/src/pages/summaryPage.tsx (hunk 4 above)
Comment (Michaeltaoma) [reply frontend/src/pages/summaryPage.tsx:36]: It's possible. We can

1. Configure [life cycle policy for s3 object](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.LifecycleRule.html)
2. Add another API to delete specific S3 objects after we fetched the S3 object.

However, this is out of the scope of this pr since this pr focus on resolving the issue. We have 5GB of free storage, which should be good for now. I can make another issue and work on that after this pr.

Comment (Hgjnnf) [reply frontend/src/pages/summaryPage.tsx:36]: Yep, sounds good! I'll resolve this comment

**Review by Hgjnnf — APPROVED** [review]
LGTM!
